# Generated by Django 3.2 on 2021-04-15 04:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytext',
            name='board_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
